{% set name = "more.forwarded" %}
{% set version = "0.2" %}
{% set sha256 = "d6e89b4990dc98fe4476d1dea3c49506a3434d5fc8118d48afaeecfcaa0595c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - morepath >0.13.2

  run:
    - python >={{ python_min }}
    - morepath >0.13.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - more
    - more.forwarded
  commands:
    - pip check

about:
  home: http://pypi.python.org/pypi/more.forwarded
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Forwarded header support for Morepath'
  description: |
    If you want to run Morepath behind a trusted proxy that sets the Forwarded
    header, you can use more.forwarded to make Morepath generate URLs that take
    this header into account.
  dev_url: https://github.com/morepath/more.forwarded

extra:
  recipe-maintainers:
    - stuertz
