travis:
  secure:
    BINSTAR_TOKEN: u7PScsgRpG8yvkrirG6Mp+w2OsVKKU65WFsRqJWHmXcBteHkRYOxU1z+kLScLDWlYsurpo9W4BmmYx0UCsXEuJchazXhnTjMUEyN9GRz7TPXilMS9hyM9NBLq08vC7dfxxuGVN1a6BwVzNR8Y+eewAU4ZWuVDBc0ZW4g7y+4cdvx60IGdGXcsrdCxShfYCYVAP6gp2jyGaCnpLPjRPglvTgdo1CTCkbwlnBFabswgqT+M3ZLB1g8HHZT4OSdPVCNOxK9PMRc4XFjN5SxYzfhQu9bpoN43zx2od0XiAw6eKnA8eX47crV7oNYE/+C/XPGYs+gExQa3pTmKViyhlO2JQYrThyEE9d0rH+PbBgS7AkUYu2ckE0Vlxeaz2Dv84xnjMrb0Dgf/bvrPhx2Zbeaqz4oxcTiUYbZ/Dj8p5qtZDaqWXZmM/aQOM63K2QJfH5dZBIeTXhjvVyw38kA5Hz1CWm8C+YpwMPHEln9MwDN0C0GFKW9a7yOCK4pHsKoCngjFbran8m2LKijed4vb8NsG9CMxW1xbhjikQEvLF22Xc/cQ8LEf9+ygXT4XV8GN+lbB8fqJamKUvcg0QngkdDuOnWPkRXy8KVoOOD8TQaaVN4hZVx6OePTx2tR+pt+01UCyZ+/MUGTynXTebhYmGcA9JzEKZnLBGhJg1Gh/WIwy1c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
