travis:
  secure:
    BINSTAR_TOKEN: KXQtt1T60pbvsLN0iSlTcp/5dUUQ2On3IXL3nZI/YsRudZ6fNdN0n4S97F7TeKuN+avVQyNciHj9NKm6CROCf72hWzMz91L2Wm0Q+ZtGz4FUXvgQzmxXeqdRilFIZ/eBrhlVuM9+aAgC4/aBy22F+J6eFeJOuqMpfkWjh2zUD3NE6da2CSuShbvgWJdrxiBccN3eoj/5KcbEh3k1znV1wiHkVnoLsM9SBcxP+lgX91duOaxIFjlqba7gfxW0g99gVU3ok+wdvJ0EkvDz0t5guOjU9oN+o9xyDaZzTAY0Ww1BvKog7mXTSC2GNiXF49kmhWn3FkuUZFaPi3peqdZN/iGqx29H2V1UmCobIHYW/a05OS/ZVlJCkyKzlFYc/gE/nxkKzkxRyMb/wPZMzQzO6jwT3PSMwCDq4Y6eVdUjACLtQjtpHjx5UXRkegklPIK0N2cualCzbVdUGZjnTn8KzYeRHnEAI/KPZsbhQi9X3dXrGy0TgXQwAVG3r79Xhn1gzmC+CYTQU+nWJk5tRMvosAXrZnC5Zu7IURJrBokp4YoX+jNNM3aGwRzwl319WkQzCuwdi6C8i+qwGZ7hIdYk5BArxoARW5P91wnpOQ0eOqMkdws30frksKO0Qya5WQHUsdLVHKrRIA4XcFZq4DWABPGktJNES+bWsk6jtweZxT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
